spring:
  application:
    name: IDENTITY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user_details
    username: root
    password: pass@word1

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      ddl-auto: update
    show-sql: true
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
server:
 port: 9045
 
